runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: vapeswag/bower_components
  static_dir: bower_components
  secure: always

- url: vapeswag/data
  static_dir: data
  secure: always

- url: vapeswag/images
  static_dir: images
  secure: always

- url: vapeswag/src
  static_dir: src
  secure: always

- url: vapeswag/service-worker.js
  static_files: service-worker.js
  upload: service-worker.js
  secure: always

- url: vpaeswag/manifest.json
  static_files: manifest.json
  upload: manifest.json
  secure: always

- url: vapeswag/.*
  static_files: index.html
  upload: index.html
  secure: always
